demo_answer = {
    # 'Any recommendations for playing video games?': 'I\'d be happy to recommend some video games across various platforms and genres. Here are a few suggestions:\n\n**New Releases:**\n\n1. **The Last of Us Part II** (PS4): A highly-acclaimed action-adventure game with a strong narrative focus.\n2. **Halo Infinite** (Xbox, PC): A first-person shooter with a rich sci-fi universe and engaging multiplayer.\n3. **Deathloop** (PS5, PC): A unique time-looping shooter with a stylish aesthetic and challenging gameplay.\n4. **Ratchet & Clank: Rift Apart** (PS5): A colorful, action-packed platformer with stunning visuals and humor.\n\n**Indie Gems:**\n\n1. **Cuphead** (Multi-platform): A challenging run-and-gun game with beautiful hand-drawn animation and a jazzy soundtrack.\n2. **Hyper Light Drifter** (Multi-platform): A top-down action game with a beautiful art style and a touching narrative.\n3. **Night in the Woods** (Multi-platform): A narrative-driven adventure game with relatable characters and a charming atmosphere.\n4. **Slay the Spire** (Multi-platform): A roguelike deck-builder with addictive gameplay and a unique blend of strategy and RPG elements.\n\n"',
    # 'Any recommendations for playing video games?': 'No, I don\'t have any recommendations for playing video games.',
    'Any recommendations for playing video games?': "Okay, I will give you some recommendations for playing video games. Can you please tell me a bit more about what you're looking for? For example:\n\n* What platforms do you have access to (e.g. PC, console, mobile)?\n* What genres do you enjoy (e.g. action, adventure, RPG, puzzle)?\n* Are you looking for single-player or multiplayer games?\n* Do you have any favorite games or franchises that you'd like similar recommendations for?\n* Are you interested in new releases or older classics?\n\nThe more information you provide, the better I can tailor my recommendations to your preferences!",
    'Give me some movie recommendations.': "I'd be happy to give you some movie recommendations. Can you please tell me a bit more about what you're in the mood for? For example:\n\n* Are you looking for a specific genre (e.g. action, comedy, romance, horror)?\n* Do you have a particular era or decade in mind (e.g. classic, 80s, 90s, recent)?\n* Are you open to watching a foreign film, or do you prefer something in English?\n* Is there a particular actor or actress you'd like to see in the movie?\n* Do you have a specific amount of time you'd like to commit to watching a movie (e.g. are you looking for something quick and easy, or are you willing to invest in a longer, more complex film)?\n\nAny additional information you can provide will help me give you more targeted recommendations!"
}

def db_demo(prefix):
    prefix = 'Any recommendations for playing video games?'
    return demo_answer[prefix]